server.port=${PORT:8081}
server.address=0.0.0.0

spring.profiles.active=live

footballapp.base-url=${APP_URL:http://localhost:8081}

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR