server.port=8081

spring.datasource.url=${FOOTBALLAPP_DB_URL}
spring.datasource.username=${FOOTBALLAPP_DB_USER}
spring.datasource.password=${FOOTBALLAPP_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver